### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by Iuke121** [hzqst/VmwareHardenedLoader#12]
When trying to build with VS 2019 I get the following build errors:
\capstone\cs.c(65,10): error C1083:  Cannot open include file: 'arch/X86/X86Module.h': No such file or directory 
2>LINK : fatal error LNK1181: cannot open input file 'capstone_static_winkernel.lib'

**Comment by hzqst** [comment]
you need to build capstone_static_winkernel project before build vmloader

**Comment by Iuke121** [comment]
The first error, "\capstone\cs.c(65,10): error C1083: Cannot open include file: 'arch/X86/X86Module.h': No such file or directory" is from building capstone_static_winkernel

**Comment by hzqst** [comment]
> The first error, "\capstone\cs.c(65,10): error C1083: Cannot open include file: 'arch/X86/X86Module.h': No such file or directory" is from building capstone_static_winkernel. There is no folder X86. And if I comment out the related lines, I get C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(429,5): error MSB6006: "CL.exe" exited with code 2.

missing files has been added to the repo.
