### ISSUE TITLE
VMProtect err

### ISSUE THREAD

**Issue by lolka13372** [hzqst/VmwareHardenedLoader#14]
I did everything as it is written does not work with vmprotect 3.3.2 - 3.3.1 you can tell me what to do with it I did not install vmtools did everything according to the instructions but still vmprotect writes that it cannot work on the virtual machine

**Comment by hzqst** [comment]
Could you provide a VMP 3.3.2 packed sample that detects vmware?

**Comment by lolka13372** [comment]
AsyncRAT + vmprotect 3.3.2 - 3.3.1
