### ISSUE TITLE
处理虚拟机不够完全

### ISSUE THREAD

**Issue by strivexjun** [hzqst/VmwareHardenedLoader#2]
大表哥好 看了下处理的的handler，发现处理不够完全。
VMP3.x他是这么来检测的
1.CPUID
2.EnumSystemFirmwareTables  GetSystemFirmwareTable
然后搜索里面3个字符串。 1. VMware 2. VirtualBox 3.Parallels

要把 这3个字符串全处理掉

**Comment by hzqst** [comment]
我这个是针对vmware的，vbox可以出门左转修改BIOS ROM更简单，都不需要挂驱动： https://github.com/hfiref0x/VBoxHardenedLoader/

**Comment by strivexjun** [comment]
大表哥给他们一起安排安排
