### ISSUE TITLE
Win 10 x64 dxdiag system resolved as vmware

### ISSUE THREAD

**Issue by pesalek** [hzqst/VmwareHardenedLoader#30]
Instaled the compiled file, service running, but dxdiag on system page shows it is a vmware and of course vm-protected sw does not work.

No VM tools installed.

Any idea what should I check?

![image](https://user-images.githubusercontent.com/12142938/84277345-a9487000-ab33-11ea-9ecc-6b27d2541fd2.png)

**Comment by charlescao460** [comment]
Reg changes: https://github.com/hzqst/VmwareHardenedLoader/issues/9#issuecomment-458390893

**Comment by pesalek** [comment]
First problem was wrong placement of parameters in .vmx file, moved to start and system tam now OK. Sencond TAB ( graphics card ) fixed by https://github.com/hzqst/VmwareHardenedLoader/issues/9#issuecomment-458390893

Thank you
