### ISSUE TITLE
driver compilation error

### ISSUE THREAD

**Issue by pensiveparrot** [hzqst/VmwareHardenedLoader#31]
![image](https://user-images.githubusercontent.com/54560136/86079714-23975080-ba5f-11ea-8ab9-281638099545.png)

**Comment by bumblebee2511** [comment]
How much version do you use vmware?

**Comment by pensiveparrot** [comment]
> How much version do you use vmware?

![image](https://user-images.githubusercontent.com/54560136/86128442-5c5f1600-baaf-11ea-815f-9e8ed83bd670.png)

**Comment by pensiveparrot** [comment]
I removed the metadata and it worked.
