### ISSUE TITLE
.vcxproj file missing Error while loading SLN/Projects

### ISSUE THREAD

**Issue by okan76** [hzqst/VmwareHardenedLoader#6]
Hey im very new in this visual studio things.

I tried to follow your steps but when i start vmloader.sln its giving error messages.

that hidden.vcxproj
       Hiddentest.vcxproj
       HiddenLib.vcxproj
       capstone_static_winkernel.vcxproj  
is missing.

Ive checkted the paths and theyre really missing. I wanted to that bypass for Vmware Detections 
to start a game which is very good protected by THEMIDA and an AntiCheat.

Could you may help me in this case. Im very new ive just some beginner experiences with coding on Python nothing else.

**Comment by hzqst** [comment]
There is something wrong with my submodule "capstone" and "hidden", you could download them from their original repo, or just try the compiled bin.
