### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by samdogo** [hzqst/VmwareHardenedLoader#8]
Hi
I am curious to know how to use this program.

I completed 1st, 2nd step

1. Does this program work only on Windows 10? my computer win7
2. Windows Driver Kit 10
    Not installed on Windows 7?
3. 3rd step, I don't know where install.bat 

I am a beginner
Can you give me a little more detail on how to use the program?

**Comment by hzqst** [comment]
1. It only works on vmware guest between windows vista and windows 10, like I said 

> For now, only Windows (vista~win10) x64 guests are supported.,

 it makes no sense to install this program in your host machine. does
> my computer win7

mean you are going to install in your host environment ?

you can find install.bat in [/bin/install.bat](https://github.com/hzqst/VmwareHardenedLoader/tree/master/bin)

**Comment by samdogo** [comment]
oh I got it thank you
